import "./globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import AuthProvider from "@/app/components/auth/Provider";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <AuthProvider>
        <body className={figtree.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
