export const metadata = {
  title: "Sign up - Spotify",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' style={{ background: "white" }}>
      <body>{children}</body>
    </html>
  );
}
